#!/bin/bash
case $PATH_INFO in *.css ) echo -e "Content-type:text/css\n" ;; * ) echo -e "Content-type:text/html\n" ;; esac
unzip -p $(echo $SCRIPT_FILENAME | sed 's|/cgi-bin/.*||')/cmssw/$(echo $PATH_INFO | cut -d/ -f2).zip $PATH_INFO

